// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/signed.proto

package signed

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Buffer struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Buffer) Reset()         { *m = Buffer{} }
func (m *Buffer) String() string { return proto.CompactTextString(m) }
func (*Buffer) ProtoMessage()    {}
func (*Buffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc9f8e64e5ade5a3, []int{0}
}

func (m *Buffer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Buffer.Unmarshal(m, b)
}
func (m *Buffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Buffer.Marshal(b, m, deterministic)
}
func (m *Buffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Buffer.Merge(m, src)
}
func (m *Buffer) XXX_Size() int {
	return xxx_messageInfo_Buffer.Size(m)
}
func (m *Buffer) XXX_DiscardUnknown() {
	xxx_messageInfo_Buffer.DiscardUnknown(m)
}

var xxx_messageInfo_Buffer proto.InternalMessageInfo

func (m *Buffer) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Buffer) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Buffer)(nil), "Buffer")
}

func init() { proto.RegisterFile("proto/signed.proto", fileDescriptor_dc9f8e64e5ade5a3) }

var fileDescriptor_dc9f8e64e5ade5a3 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x4c, 0xcf, 0x4b, 0x4d, 0xd1, 0x03, 0x73, 0x94, 0xac, 0xb8, 0xd8, 0x9c,
	0x4a, 0xd3, 0xd2, 0x52, 0x8b, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x78, 0x82, 0xc0, 0x6c, 0x21, 0x19, 0x2e, 0x4e, 0x90, 0xea, 0xc4, 0x92, 0xd2, 0xa2,
	0x54, 0x09, 0x26, 0xb0, 0x04, 0x42, 0x20, 0x89, 0x0d, 0x6c, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xbc, 0xac, 0x4d, 0x60, 0x58, 0x00, 0x00, 0x00,
}
